"""LangGraph wiring for the triggered flows.

Flow #1 + #2 - initial generation pipeline (``MEAL_PLAN_GRAPH``):

    START
      -> creative_meals
      -> decision_support_meals
           -> (invalid & retries left)  loop back to creative_meals
           -> (valid, or retries spent) creative_grocery
      -> creative_grocery
      -> decision_support_grocery
           -> (over budget & retries left) loop back to creative_grocery
           -> (within budget, or retries spent) END

Flow #3 - rejection handling (``REJECTION_GRAPH``), a SEPARATE entry point that
fires when the user rejects one meal (identified by ``rejected_meal_index``):

    START
      -> extraction_rejection            (LLM: classify into 2 branches)
           -> preference_fixable  -> propose_substitution
                                        -> swap applied  -> personalized -> END
                                        -> not usable    -> regenerate_meal -> personalized -> END
           -> constraint_violated -> regenerate_meal -> personalized -> END

``personalized`` (plain Python, DynamoDB) always runs last on both endings -
per the roadmap, the learned reason is stored regardless of which branch
handled the rejection.

Retry loops in the pipeline are bounded (MEAL_VALIDATION_MAX_RETRIES /
GROCERY_VALIDATION_MAX_RETRIES). Both graphs share ONE InMemorySaver
(``SHARED_CHECKPOINTER``) keyed by ``thread_id = session_id``, so a rejection
fired in a later HTTP request still sees the meals an earlier request
generated. The leftover-report regeneration trigger (flow #4) is NOT wired
here yet.

``invoke(payload, session_id)`` is the single dispatcher ``agent/entrypoint.py``
calls: it routes ``payload["action"]`` to the right graph and returns the
resulting state dict as-is (state in, state out).
"""

from __future__ import annotations

from langgraph.checkpoint.memory import InMemorySaver
from langgraph.graph import END, START, StateGraph

from agent.constants import GROCERY_VALIDATION_MAX_RETRIES, MEAL_VALIDATION_MAX_RETRIES
from agent.nodes.creative_grocery import creative_grocery_node
from agent.nodes.creative_meals import creative_meals_node
from agent.nodes.decision_support_grocery import decision_support_grocery_node
from agent.nodes.decision_support_meals import decision_support_meals_node
from agent.nodes.extraction_rejection import extraction_rejection_node
from agent.nodes.personalized import personalized_node
from agent.nodes.rejection_router import (
    propose_substitution_node,
    regenerate_rejected_meal_node,
    route_after_extraction,
    route_after_substitution,
)
from agent.state import MealPlanState


def route_after_meal_validation(state: MealPlanState) -> str:
    """Retry Creative(meals) while invalid and the retry budget holds, else proceed."""
    if state.get("meals_valid"):
        return "proceed"
    if int(state.get("meals_retry_count") or 0) < MEAL_VALIDATION_MAX_RETRIES:
        return "retry"
    return "proceed"  # retries spent: move on with the last attempt


def route_after_grocery_validation(state: MealPlanState) -> str:
    """Retry Creative(grocery) while over budget and the retry budget holds, else end."""
    if state.get("grocery_valid"):
        return "end"
    if int(state.get("grocery_retry_count") or 0) < GROCERY_VALIDATION_MAX_RETRIES:
        return "retry"
    return "end"  # retries spent: accept the last attempt


def build_meal_plan_graph(checkpointer: InMemorySaver | None = None):
    graph = StateGraph(MealPlanState)
    graph.add_node("creative_meals", creative_meals_node)
    graph.add_node("decision_support_meals", decision_support_meals_node)
    graph.add_node("creative_grocery", creative_grocery_node)
    graph.add_node("decision_support_grocery", decision_support_grocery_node)

    graph.add_edge(START, "creative_meals")
    graph.add_edge("creative_meals", "decision_support_meals")
    graph.add_conditional_edges(
        "decision_support_meals",
        route_after_meal_validation,
        {"retry": "creative_meals", "proceed": "creative_grocery"},
    )
    graph.add_edge("creative_grocery", "decision_support_grocery")
    graph.add_conditional_edges(
        "decision_support_grocery",
        route_after_grocery_validation,
        {"retry": "creative_grocery", "end": END},
    )

    return graph.compile(checkpointer=checkpointer or InMemorySaver())


# One checkpointer shared by both module-level graphs (see SHARED_CHECKPOINTER
# below) so a session's state - meals generated by MEAL_PLAN_GRAPH - is still
# there when REJECTION_GRAPH is invoked against the same thread_id later.


def build_rejection_graph(checkpointer: InMemorySaver | None = None):
    """Flow #3: classify a meal rejection and either substitute or regenerate it."""
    graph = StateGraph(MealPlanState)
    graph.add_node("extraction_rejection", extraction_rejection_node)
    graph.add_node("propose_substitution", propose_substitution_node)
    graph.add_node("regenerate_meal", regenerate_rejected_meal_node)
    graph.add_node("personalized", personalized_node)

    graph.add_edge(START, "extraction_rejection")
    graph.add_conditional_edges(
        "extraction_rejection",
        route_after_extraction,
        {"substitution": "propose_substitution", "regeneration": "regenerate_meal"},
    )
    graph.add_conditional_edges(
        "propose_substitution",
        route_after_substitution,
        {"done": "personalized", "regeneration": "regenerate_meal"},
    )
    graph.add_edge("regenerate_meal", "personalized")
    graph.add_edge("personalized", END)

    return graph.compile(checkpointer=checkpointer or InMemorySaver())


# --------------------------------------------------------------------------- #
# Module-level compiled graphs, and the single dispatcher entrypoint.py calls.
# --------------------------------------------------------------------------- #

# Shared across BOTH graphs and keyed by thread_id = session_id, so triggers
# fired by separate HTTP requests against the same session see one another's
# state (e.g. reject_meal needs the meals initial_generation already produced).
# Confirmed by test: two different StateGraph objects compiled against the same
# InMemorySaver instance, invoked with the same thread_id, see each other's
# checkpointed state - LangGraph's checkpointer keys by thread_id, not by which
# compiled graph wrote the checkpoint.
SHARED_CHECKPOINTER = InMemorySaver()

MEAL_PLAN_GRAPH = build_meal_plan_graph(SHARED_CHECKPOINTER)
REJECTION_GRAPH = build_rejection_graph(SHARED_CHECKPOINTER)

# Actions with a real flow behind them today. Anything else (e.g.
# report_leftovers / flow #4, the preview_grocery vs. generate_grocery split,
# substitute_response) isn't built yet - invoke() says so honestly rather than
# faking a response.
_ACTION_GRAPHS = {
    "initial_generation": MEAL_PLAN_GRAPH,
    "reject_meal": REJECTION_GRAPH,
}

# initial_generation starts a fresh planning run; these must reset even when
# re-invoked on a thread_id that already has a completed/exhausted checkpoint
# from a previous generation (e.g. "adjust plan settings" on the same session).
_INITIAL_GENERATION_RESET: dict = {
    "meals_valid": False, "meals_feedback": "", "meals_retry_count": 0,
    "grocery_valid": False, "grocery_feedback": "", "grocery_retry_count": 0,
}


def invoke(payload: dict, session_id: str) -> dict:
    """Single dispatcher entrypoint.py's HTTP handler calls: state in, state out.

    Routes ``payload["action"]`` to the graph that actually implements it,
    threading ``thread_id = session_id`` through the shared checkpointer so
    later actions on the same session see earlier ones' state. Returns the
    resulting ``MealPlanState`` as a plain dict (JSON-serializable as-is -
    every node already converts its Pydantic output to dicts before
    returning). Unknown / not-yet-built actions get a clear error dict
    instead of a crash or a faked response.
    """
    action = payload.get("action") or "initial_generation"
    graph = _ACTION_GRAPHS.get(action)
    if graph is None:
        return {
            "error": "not_implemented",
            "action": action,
            "session_id": session_id,
            "message": (
                f"Action {action!r} has no flow wired up yet. Implemented actions: "
                f"{sorted(_ACTION_GRAPHS)}."
            ),
        }

    update = {**payload, "session_id": session_id}
    if action == "initial_generation":
        update = {**_INITIAL_GENERATION_RESET, **update}

    config = {"configurable": {"thread_id": session_id}}
    return graph.invoke(update, config=config)


def _pipeline_demo() -> None:  # end-to-end demo — makes real Bedrock calls
    import json
    import uuid

    from dotenv import load_dotenv

    load_dotenv()

    sample_onboarding: MealPlanState = {
        "budget": 55.0,
        "goal": "high protein (~130g/day), around 1800 kcal/day, more vegetables and fibre",
        "dietary_restrictions": ["no pork", "no shellfish"],
        "appliances": ["microwave", "stovetop"],
        "cuisine_preferences": ["mediterranean", "japanese"],
        "living_alone_or_partner": "alone",
        "shopping_frequency_days": 4,
        "supermarket": "FairPrice",
        "leftover_ingredients": ["olive oil"],   # demo: shows already_have cross-reference
        "days_until_next_shopping": 0,
        "meals_retry_count": 0,
        "grocery_retry_count": 0,
    }

    config = {"configurable": {"thread_id": f"demo-{uuid.uuid4().hex[:8]}"}}
    print(f"Invoking meal-plan + grocery graph (thread_id={config['configurable']['thread_id']}) ...\n")

    final_state = MEAL_PLAN_GRAPH.invoke(sample_onboarding, config=config)

    print("=== run log ===")
    for entry in final_state.get("log", []):
        print(" -", entry)

    print(f"\n=== meals_valid: {final_state.get('meals_valid')} ===")
    if not final_state.get("meals_valid"):
        print("final meal feedback:", final_state.get("meals_feedback"))

    print("\n--- validated MealPlan ---")
    from agent.schemas import Meal
    from agent.tools.nutrition_calculator import calculate_meal_nutrition

    for meal in final_state.get("meals", []):
        n = meal.get("nutrition") or {}
        ings = ", ".join(f"{i['quantity']}{i['unit']} {i['name']}" for i in meal["ingredients"])
        skipped = calculate_meal_nutrition(Meal(**meal).ingredients).skipped_ingredients
        print(f"\nDay {meal['day_index']}: {meal['name']}  "
              f"({meal.get('estimated_prep_minutes', '?')} min, {meal.get('servings')} serving(s))")
        print(f"  ingredients: {ings}")
        print(f"  appliances : {meal.get('appliances_used')}")
        if n:
            print(f"  nutrition  : {n['calories']:.0f} kcal | {n['protein_g']:.0f}g protein | "
                  f"{n['carbs_g']:.0f}g carbs | {n['fats_g']:.0f}g fat | {n['fiber_g']:.0f}g fibre")
        print(f"  skipped_ingredients: {skipped or '[]  (all ingredients counted)'}")

    print(f"\n=== grocery_valid: {final_state.get('grocery_valid')} ===")
    print("grocery feedback:", final_state.get("grocery_feedback"))

    print("\n--- validated / priced / categorized GroceryList ---")
    by_category: dict[str, list[dict]] = {}
    total = 0.0
    for item in final_state.get("grocery_list", []):
        by_category.setdefault(item.get("category", "other"), []).append(item)
        if not item.get("already_have"):
            total += float(item.get("estimated_cost") or 0.0)
    for category in sorted(by_category):
        print(f"\n[{category}]")
        for item in by_category[category]:
            flag = "  (already have)" if item.get("already_have") else ""
            print(f"  {item['quantity']}{item['unit']:<4} {item['name']:<20} "
                  f"${float(item.get('estimated_cost') or 0.0):>6.2f}{flag}")
    print(f"\n  estimated total (excl. already-have): ${total:.2f}  /  budget ${sample_onboarding['budget']:.2f}")

    print("\n=== raw grocery JSON ===")
    print(json.dumps(final_state.get("grocery_list", []), indent=2))


# A meal plan resembling a real successful pipeline run, so the rejection demo
# does not have to spend two LLM calls regenerating one first.
_DEMO_PLAN: list[dict] = [
    {"name": "Garlic Chicken with Broccoli and Brown Rice", "day_index": 0, "servings": 1,
     "ingredients": [{"name": "chicken breast", "quantity": 150, "unit": "g"},
                     {"name": "broccoli", "quantity": 200, "unit": "g"},
                     {"name": "brown rice", "quantity": 75, "unit": "g"},
                     {"name": "garlic", "quantity": 5, "unit": "pcs"},
                     {"name": "olive oil", "quantity": 2, "unit": "tbsp"}],
     "appliances_used": ["stovetop"], "estimated_prep_minutes": 30, "status": "pending"},
    {"name": "Soy Tofu Stir-Fry with Carrot and Onion", "day_index": 1, "servings": 1,
     "ingredients": [{"name": "firm tofu", "quantity": 200, "unit": "g"},
                     {"name": "carrot", "quantity": 150, "unit": "g"},
                     {"name": "onion", "quantity": 100, "unit": "g"},
                     {"name": "soy sauce", "quantity": 2, "unit": "tbsp"},
                     {"name": "olive oil", "quantity": 2, "unit": "tbsp"}],
     "appliances_used": ["stovetop"], "estimated_prep_minutes": 25, "status": "pending"},
    {"name": "Oven Chicken with Sweet Potato and Broccoli", "day_index": 2, "servings": 1,
     "ingredients": [{"name": "chicken breast", "quantity": 150, "unit": "g"},
                     {"name": "sweet potato", "quantity": 150, "unit": "g"},
                     {"name": "broccoli", "quantity": 150, "unit": "g"},
                     {"name": "olive oil", "quantity": 2, "unit": "tbsp"}],
     "appliances_used": ["oven"], "estimated_prep_minutes": 40, "status": "pending"},
    {"name": "Egg and Spinach Scramble with Tomato", "day_index": 3, "servings": 1,
     "ingredients": [{"name": "egg", "quantity": 3, "unit": "pcs"},
                     {"name": "spinach", "quantity": 100, "unit": "g"},
                     {"name": "tomato", "quantity": 150, "unit": "g"},
                     {"name": "olive oil", "quantity": 1, "unit": "tbsp"}],
     "appliances_used": ["stovetop"], "estimated_prep_minutes": 15, "status": "pending"},
]


def _rejection_demo() -> None:  # makes real Bedrock calls (1 per rejection)
    import uuid

    from dotenv import load_dotenv

    load_dotenv()

    onboarding = {
        "budget": 55.0,
        "goal": "high protein, around 1800 kcal/day, more vegetables and fibre",
        "dietary_restrictions": ["no pork", "no shellfish"],
        "appliances": ["microwave", "stovetop"],   # note: NO oven
        "cuisine_preferences": ["mediterranean", "japanese"],
        "living_alone_or_partner": "alone",
        "shopping_frequency_days": 4,
        "supermarket": "FairPrice",
    }

    scenarios = [
        (0, "I'm vegetarian - can this be made without the meat?",
         "preference-based, named ingredient -> expect a clean substitution"),
        (0, "way too much garlic for me",
         "preference-based, no curated swap -> expect fallback to regeneration"),
        (2, "I don't have an oven",
         "constraint-based -> expect single-meal regeneration"),
    ]

    from agent.nodes.personalized import load_learned_preferences

    session_id = f"reject-demo-{uuid.uuid4().hex[:8]}"  # one session across all 3 scenarios
    print(f"session_id: {session_id}\n")

    for meal_index, raw_reason, note in scenarios:
        state: MealPlanState = {
            **onboarding,
            "session_id": session_id,
            "meals": [dict(m) for m in _DEMO_PLAN],
            "rejected_meal_index": meal_index,
            "rejection_reason_raw": raw_reason,
        }
        before = state["meals"][meal_index]
        cfg = {"configurable": {"thread_id": f"reject-{uuid.uuid4().hex[:8]}"}}

        print("=" * 74)
        print(f"REJECT meal {meal_index} (day {before['day_index']}): {before['name']}")
        print(f'  reason: "{raw_reason}"   [{note}]')
        print(f"  before ingredients: {[i['name'] for i in before['ingredients']]}")
        print("=" * 74)

        out = REJECTION_GRAPH.invoke(state, config=cfg)

        for entry in out.get("log", []):
            print("  -", entry)

        after = out["meals"][meal_index]
        print(f"\n  category        : {out.get('rejection_category')}")
        print(f"  reason_summary  : {out.get('rejection_reason_summary')}")
        print(f"  target_ingredient: {out.get('rejection_target_ingredient') or '(none)'}")
        print(f"  outcome         : {out.get('rejection_outcome')}")
        print(f"\n  AFTER  day {after['day_index']}: {after['name']}")
        print(f"    ingredients: {[i['name'] + ' ' + str(i['quantity']) + i['unit'] for i in after['ingredients']]}")
        print(f"    appliances : {after.get('appliances_used')}")
        n = after.get("nutrition") or {}
        if n:
            print(f"    nutrition  : {n['calories']:.0f} kcal | {n['protein_g']:.0f}g protein | "
                  f"{n['carbs_g']:.0f}g carbs | {n['fats_g']:.0f}g fat | {n['fiber_g']:.0f}g fibre")
        print()

    print("=" * 74)
    print(f"DynamoDB read-back for session_id={session_id!r}")
    print("=" * 74)
    for record in load_learned_preferences(session_id):
        print(" -", record)


if __name__ == "__main__":
    import sys

    demo = sys.argv[1] if len(sys.argv) > 1 else "pipeline"
    if demo == "rejection":
        _rejection_demo()
    else:
        _pipeline_demo()
